protocols:
  - command: alpha

accounts:
  activator:
    bootstrap_balance: '4000000000000'
    is_bootstrap_baker_account: false
    key: edsk31vznjHSSpGExDMHYASz45VZqXN4DPxvsa4hAyY8dHM28cZzp6
    type: secret
  bootstrap1:
    bootstrap_balance: '4000000000000'
    is_bootstrap_baker_account: true
    key: edsk4K663GCFQwpP9A8KmB1apLti9QdymaLSfDpZJYxF6FU7RDxTf7
    type: secret
  bootstrap2:
    bootstrap_balance: '4000000000000'
    is_bootstrap_baker_account: true
    key: edsk3TQC5LiubMxjRHPtG9C6nm36naBc48HRyCutpg7EvKEjbDXWwg
    type: secret
  bootstrap3:
    bootstrap_balance: '4000000000000'
    is_bootstrap_baker_account: true
    key: edsk4R5vSo6TcJDKzHyEpBN4J43Zoq5hqgRxZR6CfxavprMVLsx3XH
    type: secret

activation:
  protocol_hash: ProtoALphaALphaALphaALphaALphaALphaALphaALphaDdp3zK
  protocol_parameters:
    # Specific to Tenderbake
    consensus_committee_size: 67
    consensus_threshold: 45
    round_durations: [ "15", "30" ]
    liquidity_baking_subsidy: "2500000"
    liquidity_baking_sunset_level: 525600
    liquidity_baking_escape_ema_threshold: 1000000
    ########################
    baking_reward_per_endorsement:
    - '200000'
    block_security_deposit: '512000000'
    blocks_per_commitment: 4
    blocks_per_cycle: 8
    blocks_per_roll_snapshot: 4
    blocks_per_voting_period: 64
    cost_per_byte: '1000'
    # delay_per_missing_endorsement: '1'
    endorsement_reward:
    - '2000000'
    endorsement_security_deposit: '64000000'
    # endorsers_per_block: 32
    hard_gas_limit_per_block: '8000000'
    hard_gas_limit_per_operation: '800000'
    hard_storage_limit_per_operation: '60000'
    # initial_endorsers: 1
    michelson_maximum_type_size: 1000
    min_proposal_quorum: 500
    origination_size: 257
    preserved_cycles: 2
    proof_of_work_threshold: '-1'
    quorum_max: 7000
    quorum_min: 2000
    seed_nonce_revelation_tip: '125000'
    # test_chain_duration: '1966080'
    # time_between_blocks:
    # - '10'
    # - '20'
    tokens_per_roll: '8000000000'
  should_include_commitments: false
bootstrap_peers: []
expected_proof_of_work: 0
full_snapshot_url: null
images:
  tezos: tezo:latest
is_invitation: false
node_config_network:
  activation_account_name: activator
  chain_name: tenderbakenet
  genesis:
    block: BLockGenesisGenesisGenesisGenesisGenesisaa4ddfmmVAo
    protocol: PtYuensgYBb3G3x1hLLbCmcav8ue8Kyd2khADcL5LsT5R1hcXex
    timestamp: '2021-05-28T12:23:13.000000+00:00'
nodes:
  baking:
    tezos-baking-node-0:
      bake_using_account: bootstrap1
      config:
        shell:
          history_mode: archive
      is_bootstrap_node: true
    tezos-baking-node-1:
      bake_using_account: bootstrap2
      config:
        shell:
          history_mode: archive
      is_bootstrap_node: true
    tezos-baking-node-2:
      bake_using_account: bootstrap3
      config:
        shell:
          history_mode: archive
      is_bootstrap_node: false
  regular: null
rolling_snapshot_url: null
should_generate_unsafe_deterministic_data: false
zerotier_config:
  zerotier_network: null
  zerotier_token: null

tezos_k8s_images:
  utils: tqtezos/tezos-k8s-utils:4.0.0